/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlbumPackage {
  'features' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'size' : AlbumSize,
  'description' : string,
  'price' : bigint,
}
export type AlbumSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface ContactInquiry {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export type PortfolioCategory = { 'other' : string } |
  { 'event' : null } |
  { 'wedding' : null } |
  { 'maternity' : null } |
  { 'individual' : null } |
  { 'family' : null };
export interface PortfolioItem {
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'category' : PortfolioCategory,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAlbumPackages' : ActorMethod<[], undefined>,
  'clearContactInquiries' : ActorMethod<[], undefined>,
  'clearPortfolioItems' : ActorMethod<[], undefined>,
  'createAlbumPackage' : ActorMethod<[AlbumPackage], string>,
  'createPortfolioItem' : ActorMethod<[PortfolioItem], string>,
  'deleteAlbumPackage' : ActorMethod<[string], undefined>,
  'deleteContactInquiry' : ActorMethod<[string], undefined>,
  'deletePortfolioItem' : ActorMethod<[string], undefined>,
  'getAlbumPackage' : ActorMethod<[string], [] | [AlbumPackage]>,
  'getAlbumPackagesBySize' : ActorMethod<[AlbumSize], Array<AlbumPackage>>,
  'getAllAlbumPackages' : ActorMethod<[], Array<AlbumPackage>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInquiry' : ActorMethod<[string], [] | [ContactInquiry]>,
  'getPortfolioItem' : ActorMethod<[string], [] | [PortfolioItem]>,
  'getPortfolioItemsByCategory' : ActorMethod<
    [PortfolioCategory],
    Array<PortfolioItem>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPortfolioItemsByTitle' : ActorMethod<[string], Array<PortfolioItem>>,
  'submitInquiry' : ActorMethod<[ContactInquiry], string>,
  'updateAlbumPackage' : ActorMethod<[string, AlbumPackage], undefined>,
  'updatePortfolioItem' : ActorMethod<[string, PortfolioItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];