/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AlbumSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const AlbumPackage = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : AlbumSize,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const PortfolioCategory = IDL.Variant({
  'other' : IDL.Text,
  'event' : IDL.Null,
  'wedding' : IDL.Null,
  'maternity' : IDL.Null,
  'individual' : IDL.Null,
  'family' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioItem = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'category' : PortfolioCategory,
  'image' : ExternalBlob,
});
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAlbumPackages' : IDL.Func([], [], []),
  'clearContactInquiries' : IDL.Func([], [], []),
  'clearPortfolioItems' : IDL.Func([], [], []),
  'createAlbumPackage' : IDL.Func([AlbumPackage], [IDL.Text], []),
  'createPortfolioItem' : IDL.Func([PortfolioItem], [IDL.Text], []),
  'deleteAlbumPackage' : IDL.Func([IDL.Text], [], []),
  'deleteContactInquiry' : IDL.Func([IDL.Text], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
  'getAlbumPackage' : IDL.Func([IDL.Text], [IDL.Opt(AlbumPackage)], ['query']),
  'getAlbumPackagesBySize' : IDL.Func(
      [AlbumSize],
      [IDL.Vec(AlbumPackage)],
      ['query'],
    ),
  'getAllAlbumPackages' : IDL.Func([], [IDL.Vec(AlbumPackage)], ['query']),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], []),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInquiry' : IDL.Func([IDL.Text], [IDL.Opt(ContactInquiry)], []),
  'getPortfolioItem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortfolioItem)],
      ['query'],
    ),
  'getPortfolioItemsByCategory' : IDL.Func(
      [PortfolioCategory],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPortfolioItemsByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'submitInquiry' : IDL.Func([ContactInquiry], [IDL.Text], []),
  'updateAlbumPackage' : IDL.Func([IDL.Text, AlbumPackage], [], []),
  'updatePortfolioItem' : IDL.Func([IDL.Text, PortfolioItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AlbumSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AlbumPackage = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : AlbumSize,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PortfolioCategory = IDL.Variant({
    'other' : IDL.Text,
    'event' : IDL.Null,
    'wedding' : IDL.Null,
    'maternity' : IDL.Null,
    'individual' : IDL.Null,
    'family' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioItem = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'category' : PortfolioCategory,
    'image' : ExternalBlob,
  });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAlbumPackages' : IDL.Func([], [], []),
    'clearContactInquiries' : IDL.Func([], [], []),
    'clearPortfolioItems' : IDL.Func([], [], []),
    'createAlbumPackage' : IDL.Func([AlbumPackage], [IDL.Text], []),
    'createPortfolioItem' : IDL.Func([PortfolioItem], [IDL.Text], []),
    'deleteAlbumPackage' : IDL.Func([IDL.Text], [], []),
    'deleteContactInquiry' : IDL.Func([IDL.Text], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
    'getAlbumPackage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AlbumPackage)],
        ['query'],
      ),
    'getAlbumPackagesBySize' : IDL.Func(
        [AlbumSize],
        [IDL.Vec(AlbumPackage)],
        ['query'],
      ),
    'getAllAlbumPackages' : IDL.Func([], [IDL.Vec(AlbumPackage)], ['query']),
    'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], []),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInquiry' : IDL.Func([IDL.Text], [IDL.Opt(ContactInquiry)], []),
    'getPortfolioItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioItemsByCategory' : IDL.Func(
        [PortfolioCategory],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPortfolioItemsByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func([ContactInquiry], [IDL.Text], []),
    'updateAlbumPackage' : IDL.Func([IDL.Text, AlbumPackage], [], []),
    'updatePortfolioItem' : IDL.Func([IDL.Text, PortfolioItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };